<?php

namespace AppBundle\Repository;

/**
 * BibliographyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BibliographyRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllLecturerBibs()
{
    return $this->createQueryBuilder('bibliography')
        ->join('bibliography.user', 'user')
        ->Where('user.roles LIKE :role')
        ->setParameter('role', '%LECTURER%')
        ->andWhere('bibliography.status = :status')
        ->setParameter('status', 'public')
        ->getQuery()
        ->execute();
}

    public function getBibliographiesByUser($user)
    {
        return $this->createQueryBuilder('bibliography')
            ->andWhere('bibliography.user = :user')
            ->setParameter('user', $user)
            ->getQuery()
            ->execute();
    }

}
