<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ReferenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReferenceRepository extends EntityRepository
{

    public function findAllAccepted()
    {
        return $this->createQueryBuilder('reference')
            ->andWhere('reference.status = :status')
            ->setParameter('status', 'public')
            ->getQuery()
            ->execute();
    }



}
